In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score,train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [5]:
data=pd.read_csv("combined_features.csv")
data

,Unnamed: 0,Protein-Pair,Protein1_211,Protein1_116,Protein1_161,Protein1_615,Protein1_154,Protein1_544,Protein1_444,Protein1_445,...,Protein2_223,Protein2_122,Protein2_242,Protein2_212,Protein2_432,Protein2_262,Protein2_225,Protein2_622,Protein2_252,Protein2_224
0,P09798_P09798,P09798_P09798,2,15,16,9,3,3,0,2,...,0,0,0,1,1,0,1,0,1,0
1,P38717_P06782,P38717_P06782,4,21,13,10,3,4,1,2,...,0,0,0,0,0,1,0,0,1,0
2,P07342_P25605,P07342_P25605,1,18,17,9,4,2,0,0,...,0,1,0,0,0,0,0,0,0,0
3,P15790_P38930,P15790_P38930,0,3,4,3,2,2,0,3,...,0,0,0,0,0,0,0,0,0,0
4,P22035_P07269,P22035_P07269,3,22,19,7,5,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63301,P53184_P22855,P53184_P22855,0,4,7,3,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
63302,P53184_P36062,P53184_P36062,0,4,7,3,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
63303,P53184_Q08236,P53184_Q08236,0,4,7,3,0,0,0,0,...,0,0,0,1,1,0,0,0,1,0
63304,P53184_Q12331,P53184_Q12331,0,4,7,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63305,P53184_Q12527,P53184_Q12527,0,4,7,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
pairs=pd.read_csv("PairList.csv")
pairs

      Protein1 Protein2  Interacting
0       P09798   P09798            1
1       P38717   P06782            1
2       P07342   P25605            1
3       P15790   P38930            1
4       P22035   P07269            1
...        ...      ...          ...
65846   P53184   P22855            0
65847   P53184   P36062            0
65848   P53184   Q08236            0
65849   P53184   Q12331            0
65850   P53184   Q12527            0

[65851 rows x 3 columns]

In [7]:
data["Interacting"]=pairs["Interacting"]

In [8]:
features = data.drop(['Unnamed: 0', 'Protein-Pair'], axis=1)
features

,Protein1_211,Protein1_116,Protein1_161,Protein1_615,Protein1_154,Protein1_544,Protein1_444,Protein1_445,Protein1_451,Protein1_513,...,Protein2_122,Protein2_242,Protein2_212,Protein2_432,Protein2_262,Protein2_225,Protein2_622,Protein2_252,Protein2_224,Interacting
0,2,15,16,9,3,3,0,2,2,7,...,0,0,1,1,0,1,0,1,0,1
1,4,21,13,10,3,4,1,2,2,8,...,0,0,0,0,1,0,0,1,0,1
2,1,18,17,9,4,2,0,0,0,8,...,1,0,0,0,0,0,0,0,0,1
3,0,3,4,3,2,2,0,3,2,2,...,0,0,0,0,0,0,0,0,0,1
4,3,22,19,7,5,0,0,0,2,10,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63301,0,4,7,3,0,0,0,0,3,3,...,0,0,0,1,0,0,0,0,0,0
63302,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,1,0,1,0,0,0
63303,0,4,7,3,0,0,0,0,3,3,...,0,0,1,1,0,0,0,1,0,0
63304,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,0,0,0,0,0,0
63305,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,0,0,0,0,0,0

In [9]:
y=features["Interacting"]
y

0        1
1        1
2        1
3        1
4        1
        ..
63301    0
63302    0
63303    0
63304    0
63305    0
Name: Interacting, Length: 63306, dtype: int64

In [10]:
features=features.drop("Interacting", axis=1)
features

,Protein1_211,Protein1_116,Protein1_161,Protein1_615,Protein1_154,Protein1_544,Protein1_444,Protein1_445,Protein1_451,Protein1_513,...,Protein2_223,Protein2_122,Protein2_242,Protein2_212,Protein2_432,Protein2_262,Protein2_225,Protein2_622,Protein2_252,Protein2_224
0,2,15,16,9,3,3,0,2,2,7,...,0,0,0,1,1,0,1,0,1,0
1,4,21,13,10,3,4,1,2,2,8,...,0,0,0,0,0,1,0,0,1,0
2,1,18,17,9,4,2,0,0,0,8,...,0,1,0,0,0,0,0,0,0,0
3,0,3,4,3,2,2,0,3,2,2,...,0,0,0,0,0,0,0,0,0,0
4,3,22,19,7,5,0,0,0,2,10,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63301,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,1,0,0,0,0,0
63302,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,0,1,0,1,0,0
63303,0,4,7,3,0,0,0,0,3,3,...,0,0,0,1,1,0,0,0,1,0
63304,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,0,0,0,0,0,0
63305,0,4,7,3,0,0,0,0,3,3,...,0,0,0,0,0,0,0,0,0,0

In [11]:
scaler = StandardScaler()
scaled = scaler.fit_transform(features)
scaled

array([[ 0.23675002,  0.5165663 ,  0.70236748, ..., -0.36571188,
         3.26486259, -0.20393753],
       [ 1.4557079 ,  1.22231623,  0.33552739, ..., -0.36571188,
         3.26486259, -0.20393753],
       [-0.37272892,  0.86944126,  0.82464751, ..., -0.36571188,
        -0.25486411, -0.20393753],
       ...,
       [-0.98220786, -0.77730856, -0.39815278, ..., -0.36571188,
         3.26486259, -0.20393753],
       [-0.98220786, -0.77730856, -0.39815278, ..., -0.36571188,
        -0.25486411, -0.20393753],
       [-0.98220786, -0.77730856, -0.39815278, ..., -0.36571188,
        -0.25486411, -0.20393753]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(scaled, y, test_size=0.3, random_state=42)
X_train

array([[-0.37272892, -0.89493355, -1.00955293, ..., -0.36571188,
        -0.25486411, -0.20393753],
       [-0.37272892, -0.07155864, -0.15359273, ..., -0.36571188,
        -0.25486411, -0.20393753],
       [ 0.23675002, -0.54205859,  0.58008745, ...,  2.21818948,
        -0.25486411, -0.20393753],
       ...,
       [ 1.4557079 ,  0.16369134,  0.70236748, ..., -0.36571188,
        -0.25486411, -0.20393753],
       [-0.37272892, -0.54205859, -0.52043281, ..., -0.36571188,
        -0.25486411, -0.20393753],
       [-0.98220786,  0.16369134,  0.09096733, ..., -0.36571188,
        -0.25486411, -0.20393753]])

In [13]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)

# Train the model on the training set
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
predictions = knn_classifier.predict(X_test)

# Print the classification report
print("Classification Report:")
print(classification_report(y_test, predictions))

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.96      0.93     13805
           1       0.88      0.68      0.77      5187

    accuracy                           0.89     18992
   macro avg       0.88      0.82      0.85     18992
weighted avg       0.89      0.89      0.88     18992

In [14]:
# Define the parameter grid for the grid search
param_grid = {
    'n_neighbors': [3, 5, 7, 9],  # Adjust as needed
    'weights': ['uniform', 'distance'],  # Weighting scheme
    'p': [1, 2]  # Power parameter for the Minkowski distance (1 for Manhattan, 2 for Euclidean)
}

# Initialize the KNN classifier
knn_classifier = KNeighborsClassifier()

# Perform grid search with 5-fold cross-validation
grid_search = GridSearchCV(knn_classifier, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(scaled, y)

# Print the best parameters and corresponding accuracy
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy: {:.2f}".format(grid_search.best_score_))

# Train the model on the entire training set using the best parameters
best_knn_classifier = grid_search.best_estimator_
best_knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
predictions = best_knn_classifier.predict(X_test)

# Print the classification report
print("Classification Report:")
print(classification_report(y_test, predictions))

Best Parameters: {'n_neighbors': 7, 'p': 1, 'weights': 'distance'}
Best Accuracy: 0.83
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.97      0.93     13805
           1       0.90      0.70      0.78      5187

    accuracy                           0.90     18992
   macro avg       0.90      0.83      0.86     18992
weighted avg       0.90      0.90      0.89     18992